config/routes.rb
NewRailsPj::Application.routes.draw do
  devise_for :users
 resources :stores
  

   get '/icecreams', to: 'ice_creams#new'
   post '/icecreams', to: 'ice_creams#create', as: 'ice_creams'
    
    
root to: 'stores#index'

end

app/models/ice_cream.rb
class IceCream < ActiveRecord::Base
    has_many :StoreIceCreams
    has_many :Stores, through: :StoreIceCreams
    
end

app/models/store.rb
class Store < ActiveRecord::Base
    has_many :StoreIceCreams
    has_many :IceCreams, through: :StoreIceCreams

    validates :name, presence: true
    
    #after_create :notify_admin
    private
    
    
end

app/models/store_ice_cream.rb
class StoreIceCream < ActiveRecord::Base
    belongs_to :Store
    belongs_to :IceCream
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    #mount_uploader :picture, PictureUploader
    
   # after_create :notify_admin
    #private
    
    #def notify_admin
        #UserMailer.notify_admin_about_new_user(self).deliver
 #       end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
    
    before_filter :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/ice_creams_controller.rb
class IceCreamsController < ApplicationController
    
    def new
        @icecream = IceCream.new
     
        end
    
    def create
        safe_params = params.require(:ice_cream).permit(:flavor)
            @icecream = IceCream.new 
            safe_params
            if @icecream.save
                redirect_to stores_path
                
                else
               flash[:notice]= "Ice cream Didn't Save!!"
                
                render :new
        end
    end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render action: 'show', status: :created, location: @store }
      else
          flash[:error] = "There was a problem adding the name."
        format.html { render action: 'new' }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.where(id: params[:id]).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:name, :address, :ice_cream_brands, :flavor, :description, :text)
    end
    
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stores_helper.rb
module StoresHelper
    
    def short_descrip store
    truncate store.description, length: 50
        end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/ice_creams/new.html.erb

<h1>Add Unlisted Brand or Flavor</h1>

<%=form_for @icecream do |form| %>

<%=form.label :store, "Put your flavor here" %>

<%= form.text_field :flavor %>

<br/>

<%=form.submit "Name your flavor!" %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewRailsPj</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
            <a href="#" class="brand">Icecream Reviews</a>
                <ul class="nav">
               <% if user_signed_in? %>
                 <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
               <% else %>
 <li><%= link_to 'Log In', new_user_session_path %></li>
               <% end %>
                    <li><%= link_to "All Stores", stores_path %></li>
                    <li><%= link_to "Add Unlisted Flavors", ice_creams_path %></li>
                </ul>
               
            </div>
        </div>
    </div>
    <div class="container">
        <% flash.each do |type, message| %>
        <div class="alert flash <%= type %>">
        <%= message %>
        </div>
        <% end %>
<%= yield %>
</div>
</body>
</html>

app/views/stores/_form.html.erb
<%= form_for(@store) do |f| %>
  <% if @store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% @store.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :ice_cream_brands %><br>
    <%= f.text_field :ice_cream_brands %>
  </div>
  <div class="field">
    <%= f.label :flavor %><br>
    <%= f.text_field :flavor %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing store</h1>

<%= render 'form' %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/icecreamlist.html.erb
<

app/views/stores/index.html.erb
<h1>Listing Stores</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Ice cream brands</th>
      <th>Flavor</th>
      <th>Description</th>
      <th>Text</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
      
    <% @stores.each do |store| %>
      <tr>
        <td><%= store.name %></td>
        <td><%= store.address %></td>
        <td><%= store.ice_cream_brands %></td>
        <td><%= store.flavor %></td>
        <td><%= short_descrip store %></td>
        <td><%= store.text %></td>
        <td><%= link_to 'Show', store %></td>
        <td><%= link_to 'Edit', edit_store_path(store) %></td>
        <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
       
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "New Store", new_store_path %>

app/views/stores/new.html.erb
<h1>New store</h1>

<%= render 'form' %>
<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @store.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @store.address %>
</p>

<p>
  <strong>Ice cream brands:</strong>
  <%= @store.ice_cream_brands %>
</p>

<p>
  <strong>Flavor:</strong>
  <%= @store.flavor %>
</p>

<p>
  <strong>Description:</strong>
  <%= @store.description %>
</p>

<p>
  <strong>Text:</strong>
  <%= @store.text %>
</p>

<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>